# escape=`
FROM microsoft/dotnet-framework:4.7.1-sdk-windowsservercore-ltsc2016

LABEL name="microsoft/vsts-agent:windows-core-ltsc2016" `
      version="0.0.1"

ENV HTTP_PROXY=$HTTP_PROXY `
    HTTPS_PROXY=$HTTPS_PROXY `
    NO_PROXY=$NO_PROXY `
    WINDOWS_IMAGE_VERSION=ltsc2016

RUN mkdir C:\TFS; mkdir C:\Setup

WORKDIR C:/Setup

COPY setup/ .

RUN netsh.exe winhttp set proxy proxy-server="http=%HTTP_PROXY%;https=%HTTPS_PROXY%" bypass-list="%NO_PROXY%"; `
 .\setprofile.ps1

WORKDIR C:\

